///**
//  * Generated by smali2java 1.0.0.558
//  * Copyright (C) 2013 Hensence.com
//  */
//
//package com.lockscreen.view;
//
//import android.view.View;
//import android.graphics.RectF;
//import android.graphics.Bitmap;
//import android.graphics.Paint;
//import android.graphics.Path;
//import android.content.Context;
//import android.util.AttributeSet;
//import android.graphics.Canvas;
//import android.graphics.BlurMaskFilter;
//import android.graphics.MaskFilter;
//import ginlemon.locker.tool;
//import android.content.res.AssetManager;
//import android.graphics.Typeface;
//import android.graphics.Rect;
//import java.util.Locale;
//import android.graphics.BitmapFactory;
//import android.content.res.Resources;
//
//public class FuturaView extends View {
//    static final int CYAN = -0x1;
//    static final int LIGHTCYAN = -0xff5704;
//    static final int LIGHTORANGE = -0x7500;
//    static final int ORANGE = -0x3d9a;
//    Bitmap bbattery;
//    Bitmap bcamera;
//    Bitmap biud;
//    Bitmap bnetwork;
//    Bitmap bunlock;
//    int y;
//    Path path = new Path();
//    RectF battery = new RectF();
//    int strokewidth = 0x0;
//    int batperc = 0x0;
//    int signal = 0x0;
//    String time = "00:00";
//    String data = "LUN 1 JAN 2024";
//    
//    public FuturaView(Context context) {
//        super(context);
//        init();
//    }
//    
//    public FuturaView(Context context, AttributeSet attrs) {
//        super(context, attrs);
//        init();
//    }
//    
//    public FuturaView(Context context, AttributeSet attrs, int defStyleAttr) {
//        super(context, attrs, defStyleAttr);
//        init();
//    }
//    
//    public void init() {
//        if(tool.atLeast(0xb)) {
//            setLayerType(0x1, 0x0);
//        }
//    }
//    int width = 0x0;
//    Paint paint = 0x0;
//    Paint blur = 0x0;
//    
//    public void setPaints() {
//        paint = new Paint();
//        paint.setStrokeWidth((float)strokewidth);
//        paint.setStyle(Paint.Style.STROKE);
//        paint.setAntiAlias(true);
//        blur = new Paint();
//        blur.setStrokeWidth((float)strokewidth);
//        blur.setStyle(Paint.Style.STROKE);
//        blur.setAntiAlias(true);
//        BitmapFactory.Options options = new BitmapFactory.Options();
//        options.inScaled = false;
//        bnetwork = BitmapFactory.decodeResource(getContext().getResources(), 0x7f020050, options);
//        bbattery = BitmapFactory.decodeResource(getContext().getResources(), 0x7f02001c, options);
//        bcamera = BitmapFactory.decodeResource(getContext().getResources(), 0x7f020020, options);
//        bunlock = BitmapFactory.decodeResource(getContext().getResources(), 0x7f02004b, options);
//    }
//    int frame = 0x0;
//    int unit = 0x0;
//    
//    protected void onDraw(Canvas canvas) {
//        unit = canvas.getHeight();
//        if(paint == null) {
//            setPaints();
//        }
//        drawClock(canvas);
//        drawBattery((float)batperc, canvas);
//        drawNetwork(signal, canvas);
//        drawIcons(canvas);
//    }
//    
//    void drawClock(Canvas canvas) {
//        int clockY = tool.dpToPx(93.0f);
//        int dateY = tool.dpToPx(125.0f);
//        data = data.toUpperCase(Locale.getDefault());
//        Paint p = new Paint();
//        p.setColor(-0xff5704);
//        p.setTextSize((float)tool.dpToPx(0.0f));
//        p.setTextAlign(Paint.Align.CENTER);
//        p.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "light.ttf"));
//        p.setAntiAlias(true);
//        BlurMaskFilter mBlur = new BlurMaskFilter((float)tool.dpToPx(4.0f), "light.ttf");
//        p.setMaskFilter(mBlur);
//        canvas.drawText(time, (float)(canvas.getWidth() / 0x2), (float)clockY, p);
//        p.setColor(-0x7500);
//        p.setTextSize((float)tool.dpToPx(0.0f));
//        p.setTextScaleX(1.1f);
//        canvas.drawText(data, (float)(canvas.getWidth() / 0x2), (float)dateY, p);
//        p.setColor(-0x1);
//        p.setTextScaleX(1.0f);
//        p.setMaskFilter(0x0);
//        p.setTextSize((float)tool.dpToPx(0.0f));
//        canvas.drawText(time, (float)(canvas.getWidth() / 0x2), (float)clockY, p);
//        p.setColor(-0x3d9a);
//        p.setTextSize((float)tool.dpToPx(0.0f));
//        p.setTextScaleX(1.1f);
//        canvas.drawText(data, (float)(canvas.getWidth() / 0x2), (float)dateY, p);
//    }
//    
//    void drawSwitcher(int perc, Canvas canvas) {
//        paint.setColor(-0x3d9a);
//        blur.setColor(-0x7500);
//        int radius = tool.dpToPx(25.0f);
//        battery.set((float)((canvas.getWidth() / 0x2) - radius), (float)(((canvas.getHeight() / 0x2) - radius) + y), (float)((canvas.getWidth() / 0x2) + radius), (float)(((canvas.getHeight() / 0x2) + radius) + y));
//        paint.setStrokeWidth((float)tool.dpToPx(0.0f));
//        blur.setStrokeWidth((float)tool.dpToPx(0.0f));
//        BlurMaskFilter mBlur = new BlurMaskFilter((float)tool.dpToPx(0.0f), (float)tool.dpToPx(0.0f));
//        blur.setMaskFilter(mBlur);
//        path.reset();
//        path.arcTo(battery, -70.0f, 0.0f);
//        canvas.drawPath(path, blur);
//        canvas.drawPath(path, paint);
//        path.reset();
//        path.arcTo(battery, 110.0f, 0.0f);
//        canvas.drawPath(path, blur);
//        canvas.drawPath(path, paint);
//    }
//    
//    void drawBattery(float perc, Canvas canvas) {
//        path.reset();
//        int radius = (int)((float)unit * 0x3dcccccd);
//        strokewidth = (int)((float)unit * 0x3ca3d70a);
//        paint.setStrokeWidth((float)strokewidth);
//        paint.setStrokeCap(Paint.Cap.SQUARE);
//        blur.setStrokeWidth((float)strokewidth);
//        paint.setColor(-0x3d9a);
//        blur.setColor(-0x7500);
//        BlurMaskFilter mBlur = new BlurMaskFilter((float)strokewidth, -0x7500);
//        blur.setMaskFilter(mBlur);
//        battery.set((float)((canvas.getWidth() / 0x2) - radius), (float)((canvas.getHeight() / 0x2) - radius), (float)((canvas.getWidth() / 0x2) + radius), (float)((canvas.getHeight() / 0x2) + radius));
//        if(perc >= 99.0f) {
//            perc = 99.0f;
//            path.addCircle((float)(canvas.getWidth() / 0x2), (float)(canvas.getHeight() / 0x2), (float)radius, Path.Direction.CCW);
//        } else if(perc == 0x0) {
//            path.addCircle((float)(canvas.getWidth() / 0x2), (float)(canvas.getHeight() / 0x2), (float)radius, Path.Direction.CCW);
//            paint.setAlpha(0x40);
//            blur.setAlpha(0x40);
//        } else {
//            path.arcTo(battery, -90.0f, (-360.0f * (perc / 100.0f)));
//        }
//        canvas.drawPath(path, blur);
//        canvas.drawPath(path, paint);
//        Paint blurtext = new Paint();
//        blurtext.setTextScaleX(1.1f);
//        blurtext.setColor(-0x7500);
//        blurtext.setTextSize((float)tool.dpToPx(16.0f));
//        blurtext.setTextAlign(Paint.Align.CENTER);
//        BlurMaskFilter mBlur = new BlurMaskFilter((float)tool.dpToPx(2.0f), paint);
//        blurtext.setMaskFilter(mBlur);
//        blurtext.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "light.ttf"));
//        canvas.drawText("%", (float)(((canvas.getWidth() / 0x2) - radius) - tool.dpToPx(50.0f)), tool.dpToPx(50.0f), blurtext);
//        ((canvas.getHeight() / 0x2) + tool.dpToPx(5.0f)) = (float)((canvas.getHeight() / 0x2) + tool.dpToPx(5.0f));
//        Paint text = new Paint();
//        text.setTextScaleX(1.1f);
//        text.setColor(-0x3d9a);
//        text.setTextSize((float)tool.dpToPx(16.0f));
//        text.setTextAlign(Paint.Align.CENTER);
//        text.setDither(true);
//        text.setAntiAlias(true);
//        text.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "light.ttf"));
//        canvas.drawText("%", (float)(((canvas.getWidth() / 0x2) - radius) - tool.dpToPx(50.0f)), tool.dpToPx(50.0f), text);
//        ((canvas.getHeight() / 0x2) + tool.dpToPx(5.0f)) = (float)((canvas.getHeight() / 0x2) + tool.dpToPx(5.0f));
//        canvas.drawBitmap(bbattery, 0x0, localRectF1, (float)(((canvas.getWidth() / 0x2) - radius) - tool.dpToPx(82.0f)));
//        Paint localPaint2 = new Paint();
//    }
//    
//    void drawNetwork(int perc, Canvas canvas) {
//        path.reset();
//        int radius = (int)((float)unit * 0x3e051eb8);
//        strokewidth = (int)((float)unit * 0x3c03126f);
//        paint.setStrokeWidth((float)strokewidth);
//        paint.setStrokeCap(Paint.Cap.ROUND);
//        blur.setStrokeWidth((float)strokewidth);
//        paint.setColor(-0x1);
//        blur.setColor(-0xff5704);
//        BlurMaskFilter mBlur = new BlurMaskFilter((float)strokewidth, -0xff5704);
//        blur.setMaskFilter(mBlur);
//        battery.set((float)((canvas.getWidth() / 0x2) - radius), (float)((canvas.getHeight() / 0x2) - radius), (float)((canvas.getWidth() / 0x2) + radius), (float)((canvas.getHeight() / 0x2) + radius));
//        if(perc >= 0x63) {
//            perc = 0x63;
//            path.addCircle((float)(canvas.getWidth() / 0x2), (float)(canvas.getHeight() / 0x2), (float)radius, Path.Direction.CCW);
//        } else if(perc == 0) {
//            path.addCircle((float)(canvas.getWidth() / 0x2), (float)(canvas.getHeight() / 0x2), (float)radius, Path.Direction.CCW);
//            paint.setAlpha(0x40);
//            blur.setAlpha(0x40);
//        } else {
//            path.arcTo(battery, -90.0f, (360.0f * ((float)perc / 100.0f)));
//        }
//        canvas.drawPath(path, blur);
//        canvas.drawPath(path, paint);
//        paint.setAlpha(0xff);
//        blur.setAlpha(0xff);
//        paint.setStrokeWidth((float)tool.dpToPx(3.5f));
//        blur.setStrokeWidth((float)tool.dpToPx(3.5f));
//        path.reset();
//        path.addCircle((float)(canvas.getWidth() / 0x2), (float)(canvas.getHeight() / 0x2), (float)(radius / 0x2), Path.Direction.CCW);
//        canvas.drawPath(path, blur);
//        canvas.drawPath(path, paint);
//        Paint blurtext = new Paint();
//        blurtext.setTextScaleX(1.1f);
//        blurtext.setColor(-0xff5704);
//        blurtext.setTextSize((float)tool.dpToPx(16.0f));
//        blurtext.setTextAlign(Paint.Align.CENTER);
//        BlurMaskFilter mBlur = new BlurMaskFilter((float)tool.dpToPx(2.0f), paint);
//        blurtext.setMaskFilter(mBlur);
//        blurtext.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "light.ttf"));
//        canvas.drawText("%", (float)(((canvas.getWidth() / 0x2) + radius) + tool.dpToPx(30.0f)), tool.dpToPx(30.0f), blurtext);
//        ((canvas.getHeight() / 0x2) + tool.dpToPx(5.0f)) = (float)((canvas.getHeight() / 0x2) + tool.dpToPx(5.0f));
//        Paint text = new Paint();
//        text.setTextScaleX(1.1f);
//        text.setColor(-0x1);
//        text.setTextSize((float)tool.dpToPx(16.0f));
//        text.setTextAlign(Paint.Align.CENTER);
//        text.setAntiAlias(true);
//        text.setTypeface(Typeface.createFromAsset(getContext().getAssets(), "light.ttf"));
//        canvas.drawText("%", (float)(((canvas.getWidth() / 0x2) + radius) + tool.dpToPx(30.0f)), tool.dpToPx(30.0f), text);
//        ((canvas.getHeight() / 0x2) + tool.dpToPx(5.0f)) = (float)((canvas.getHeight() / 0x2) + tool.dpToPx(5.0f));
//        canvas.drawBitmap(bnetwork, 0x0, localRectF1, (float)(((canvas.getWidth() / 0x2) + radius) + tool.dpToPx(50.0f)));
//        Paint localPaint2 = new Paint();
//    }
//    
//    void drawIcons(Canvas canvas) {
//        float radius = (float)unit * 0x3e4fdf3b;
//        float height = (float)unit * 0x3d8f5c29;
//        float width = height * 0x3f35c28f;
//        Paint iconpaint = new Paint();
//        iconpaint.setFilterBitmap(true);
//        canvas.drawBitmap(bcamera, 0x0, localRectF1, iconpaint);
//        canvas.drawBitmap(bunlock, 0x0, localRectF1, iconpaint);
//    }
//}
